Disable sysctl when building libevents (#12658)
Make the libevents library built on CentOS portable to Ubuntu.

## Problem Summary(Required) ：

When libevents is built on CentOS, it will detect sysctl libraries and try to make use of that.

Specifically, [`arc4random.c`](https://github.com/libevent/libevent/blob/3ec3b469b8d091837a1d1309ac0cdffa6a76e1d4/arc4random.c#L186) will use a different implementation when compiled with sysctl.

This causes a problem if we simply copy the `libevent.a` built on CentOS (the starrocks-dev-env docker is built by CentOS) to Ubuntu because Ubuntu does not have the sysctl libraries.

This will cause a linker error:

```
var/local/thirdparty/src/libevent-24236aed01798303745470e6c498bf606e88724a/./arc4random.c:192: undefined reference to `sysctl'
```

In this PR, we extend the libevent patch to disable sysctl when configuring the libevent library build. I have verified that the libevent library built on CentOS can now be ported to Ubuntu without linker error.